### ISSUE TITLE
Xul conversion: most (not all!!) overlays have been removed

### ISSUE THREAD

**Issue by opto** [thundernest/developer-docs#28]
Xul conversion document:

It States that overlays in TB have been removd and recommends to use Messenger.xul.
That Statement is not quite correct.
For example searchdialog.xul still exists in 68b1.
So Maybe state *most* overlays have been removed.
I would have saved me a few hours of wonderment and Code analysis.
Thanks Klaus

**Comment by mkmelin** [comment]
No, all overlays have been removed. Their names may not have been changed, but the whole overlay mechanism that used to be part of XUL was removed, and the old overlays now usually just build-time included.

**Comment by jobisoft** [comment]
@opto: What I wanted to point out in the guide was, that TB no longer overlays "itself". We had a couple of places where elements of Thunderbird (like the address book) that included XUL files that overlayed some other Thunderbird (XUL-) files. These overlays are all gone now and the stuff that was added via overlay is now just part of the "root" (XUL-) file ("root" as in root of the old overlay-chain).

Now if your add-on overlayed one of these overlay files which are no longer there, your addon will fail, because the file it wants to overlay does not exists. You must instead overlay the corresponding "root" XUL file now.

Messenger.xul was just one example (being the root of the former mailWindowOverlay.xul)

TB is still using XUL.
TB is no longer using XUL overlaying.
Add-on currently can still use XUL overlaying.

**Comment by opto** [comment]
For an Addon author, it is not really relevant whether TB internally still uses overlays.
But Thanks for the clarification.

To a non native speaker the Statement may imply that there are now no other xul files than Messenger.xul that I might have to overlay.
But there is, for example, searchdialog.xul.  There may be others. 
So the path for conversion might be:
Create the json. Check whether it works. If not, find out with what to replace the xul files you overlayed. Messenger.xul could be a good start if your xul disappeared.
Looking at the Code is not so easy. The ftp Code expands to greater 2.5 GB, DXR seems outdated and nobody answered my question elsewhere whether searchfox comm central is the Beta.
